### ISSUE TITLE
Button Exit

### ISSUE THREAD

**Issue by Just1uckk** [Just1uckk/antony-rep#1]
Delete exit button from login page.
Create normal style for this button.
Maybe replace to dropdown button.
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/79c88aaa-79ec-4b03-be09-60a8a9918d91)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/6665ade2-4afb-4048-ae9c-9cba0293f081)
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/d4fffe9c-41ec-4403-8849-83ebc73a7456)
