### ISSUE TITLE
Error Alert User

### ISSUE THREAD

**Issue by Just1uckk** [Just1uckk/antony-rep#11]
Dont use Alert. Используй всплывающие сообщения для этого, как при ошибке авторизации.
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/60ddebe1-bb69-4158-ab73-67b80e7a8ebf)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/5ac76734-41fa-4a16-97aa-a3c7c25c672b)
