### ISSUE TITLE
Material Tab

### ISSUE THREAD

**Issue by Just1uckk** [Just1uckk/antony-rep#16]
Адекватно оформить и убрать лишнее
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/b2fbd8c2-b80b-4d10-a43a-5acee9cd5cd5)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/e095b785-1163-4fbc-abdc-e375b4518710)
