### ISSUE TITLE
Change Title and IMG

### ISSUE THREAD

**Issue by Just1uckk** [Just1uckk/antony-rep#17]
Change name of the website and change preview image
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/16ce9644-6edd-4af0-b3c3-f4605ceaf5fd)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/a380aef1-2944-4033-a676-1cc492ab3545)
