### ISSUE TITLE
Customize errors 

### ISSUE THREAD

**Issue by Just1uckk** [Just1uckk/antony-rep#3]
Style this errors.
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/12f98ed1-34b1-4a23-a2e7-d19d5f3a9688)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/05f65ce3-eaf0-4df0-bd53-f049e8674f16)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/60ecd414-1935-4a95-804e-92ec5e5f5db7)
