### ISSUE TITLE
Capital letter

### ISSUE THREAD

**Issue by Just1uckk** [Just1uckk/antony-rep#4]
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/98a296db-3ddb-42db-ab4a-914e1f35eacc)

**Comment by Just1uckk** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/104012696/6b158e1a-2008-4a2c-93f0-223036e3232b)

**Comment by Livadnij** [comment]
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/7645bd26-7f10-4936-85c8-a15ce6ad7810)
![image](https://github.com/Just1uckk/antony-rep/assets/123575355/9c424296-1aaa-4a8d-b6d1-614c9991599d)
